// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwFwxSv-DVAGaNe8WLsF-rLCDc6RHAg64',
    appId: '1:650960577573:web:e3578c6949552ba6e94bcc',
    messagingSenderId: '650960577573',
    projectId: 'projectrider-e0473',
    authDomain: 'projectrider-e0473.firebaseapp.com',
    storageBucket: 'projectrider-e0473.appspot.com',
    measurementId: 'G-47LDG5KBL0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGevs9yNpQLZwJlBrwsQ4xPvtQOGwkC3c',
    appId: '1:650960577573:android:dde0b1ef93e12a3be94bcc',
    messagingSenderId: '650960577573',
    projectId: 'projectrider-e0473',
    storageBucket: 'projectrider-e0473.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTzYa7b5aMeoNbqGWyu7iHZ6svLh4r0Mw',
    appId: '1:650960577573:ios:e7fd88324134f3e9e94bcc',
    messagingSenderId: '650960577573',
    projectId: 'projectrider-e0473',
    storageBucket: 'projectrider-e0473.appspot.com',
    iosBundleId: 'com.example.flutterDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTzYa7b5aMeoNbqGWyu7iHZ6svLh4r0Mw',
    appId: '1:650960577573:ios:e7fd88324134f3e9e94bcc',
    messagingSenderId: '650960577573',
    projectId: 'projectrider-e0473',
    storageBucket: 'projectrider-e0473.appspot.com',
    iosBundleId: 'com.example.flutterDelivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwFwxSv-DVAGaNe8WLsF-rLCDc6RHAg64',
    appId: '1:650960577573:web:0a10d4767e342800e94bcc',
    messagingSenderId: '650960577573',
    projectId: 'projectrider-e0473',
    authDomain: 'projectrider-e0473.firebaseapp.com',
    storageBucket: 'projectrider-e0473.appspot.com',
    measurementId: 'G-V116GCP51J',
  );
}
